/** @deprecated Use `@/design-system` tokens and theme */
import { darkTheme } from '@/design-system';

export const colors = {
  background: darkTheme.colors.background.primary,
  backgroundSecondary: darkTheme.colors.background.secondary,
  surface: darkTheme.colors.card.default,
  surfaceElevated: darkTheme.colors.card.elevated,
  surfaceHighlight: darkTheme.colors.card.elevated,
  primary: darkTheme.colors.brand.primary,
  primaryLight: darkTheme.colors.brand.primaryLight,
  primaryDark: darkTheme.colors.brand.primaryDark,
  secondary: darkTheme.colors.brand.accent,
  secondaryLight: darkTheme.colors.brand.accentLight,
  secondaryDark: darkTheme.colors.brand.primaryDark,
  accent: darkTheme.colors.brand.accent,
  accentLight: darkTheme.colors.brand.accentLight,
  success: darkTheme.colors.status.success,
  successMuted: darkTheme.colors.status.successMuted,
  warning: darkTheme.colors.status.warning,
  warningMuted: darkTheme.colors.status.warningMuted,
  error: darkTheme.colors.status.danger,
  errorMuted: darkTheme.colors.status.dangerMuted,
  info: darkTheme.colors.status.info,
  textPrimary: darkTheme.colors.text.primary,
  textSecondary: darkTheme.colors.text.secondary,
  textMuted: darkTheme.colors.text.muted,
  textInverse: darkTheme.colors.text.inverse,
  border: darkTheme.colors.border.default,
  borderLight: darkTheme.colors.border.subtle,
  divider: darkTheme.colors.border.subtle,
  overlay: darkTheme.colors.overlay,
  transparent: darkTheme.colors.transparent,
  gradient: {
    primary: darkTheme.colors.brand.gradient,
    secondary: darkTheme.colors.gradients.ai,
    surface: darkTheme.colors.gradients.surface,
    premium: darkTheme.colors.gradients.premium,
  },
  tabBar: darkTheme.colors.tabBar,
} as const;
