export const STORAGE_KEYS = {
  careerProfile: '@careerpilot/career-profile',
  onboardingStep: '@careerpilot/onboarding-step',
  userAccount: '@careerpilot/user-account',
  userSession: '@careerpilot/user-session',
  cvSentEntries: '@careerpilot/cv-sent-entries',
  applicationEntries: '@careerpilot/application-entries',
  cvActionsTracking: '@careerpilot/cv-actions-tracking',
  appStreak: '@careerpilot/app-streak',
  interviewSessions: '@careerpilot/interview-sessions',
  realInterviews: '@careerpilot/real-interviews',
  savedJobs: '@careerpilot/saved-jobs',
  jobSearchPreferences: '@careerpilot/job-search-preferences',
  jobMatchApplications: '@careerpilot/job-match-applications',
  onboardingAssessment: '@careerpilot/onboarding-assessment',
  premiumStatusSimulated: 'premium_status_simulated',
  usageLimits: '@careerpilot/usage-limits',
  aiChatHistory: 'ai_chat_history',
  lastCloudSync: '@careerpilot/last-cloud-sync',
} as const;
